services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: booksapi
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: api_books
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    container_name: booksapi-redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "6378:6379"
    volumes:
      - ./redis-data:/bitnami/redis/data
